import * as ort from 'onnxruntime-web/wasm';
import { fetchJson, assetUrl } from './fetchJson';

// This file was generated by ChatGPT based on a strict and detailed outline that I created.

type SnapshotRow = {
  date: string;
  teamId: number;
  features: number[];
};

type SnapshotSeasonFile = {
  season: number;
  featureNames: string[];
  rows: SnapshotRow[];
};

type RawModelMeta = {
  team_id_to_index?: Record<string, number>;
  teamIdToIndex?: Record<string, number>;
  means?: number[];
  stds?: number[];
  featureCols?: string[];
  feature_cols?: string[];
  inputNames?: string[];
  input_names?: string[];
  outputNames?: string[];
  output_names?: string[];
};

export type ModelMeta = {
  teamIdToIndex: Record<string, number>;
  means: number[];
  stds: number[];
  featureCols: string[];
  inputNames: string[];
  outputNames: string[];
};

export type PredictInputs = {
  season: number;
  gameDate: string;
  team1Id: number;
  team2Id: number;
  homeIndicator: number;
};

export type UpcomingPredictInputs = {
  team1Id: number;
  team2Id: number;
  homeIndicator: number;
  featureNames: string[];
  team1Features: number[];
  team2Features: number[];
};

export type PredictResult = {
  team1Score: number;
  team2Score: number;
};

// GitHub Pages does not provide the cross-origin isolation headers needed
// for multi-threaded WASM, so force single-threaded inference.
ort.env.wasm.numThreads = 1;

// Only override the binary location.
// The ONNX Runtime JavaScript module itself stays bundled by Vite.
ort.env.wasm.wasmPaths = {
  wasm: assetUrl('ort/ort-wasm-simd-threaded.wasm'),
};

let sessionPromise: Promise<ort.InferenceSession> | null = null;
let modelMetaPromise: Promise<ModelMeta> | null = null;
const snapshotCache = new Map<number, Promise<SnapshotSeasonFile>>();

async function getSession(): Promise<ort.InferenceSession> {
  if (!sessionPromise) {
    sessionPromise = ort.InferenceSession.create(assetUrl('model/model.onnx'), {
      executionProviders: ['wasm'],
    });
  }
  return sessionPromise;
}

function normalizeModelMeta(raw: RawModelMeta): ModelMeta {
  const teamIdToIndex = raw.team_id_to_index ?? raw.teamIdToIndex;
  const means = raw.means ?? [];
  const stds = raw.stds ?? [];
  const featureCols = raw.featureCols ?? raw.feature_cols ?? [];
  const inputNames = raw.inputNames ?? raw.input_names ?? ['x_cont', 'team1_id', 'team2_id'];
  const outputNames = raw.outputNames ?? raw.output_names ?? ['pred_scores'];

  if (!teamIdToIndex) {
    throw new Error('model_meta.json is missing team_id_to_index/teamIdToIndex');
  }
  if (!means.length || !stds.length) {
    throw new Error('model_meta.json is missing means/stds');
  }
  if (!featureCols.length) {
    throw new Error('model_meta.json is missing featureCols/feature_cols');
  }

  return {
    teamIdToIndex,
    means,
    stds,
    featureCols,
    inputNames,
    outputNames,
  };
}

async function getModelMeta(): Promise<ModelMeta> {
  if (!modelMetaPromise) {
    modelMetaPromise = fetchJson<RawModelMeta>('model/model_meta.json').then(normalizeModelMeta);
  }
  return modelMetaPromise;
}

async function getSeasonSnapshot(season: number): Promise<SnapshotSeasonFile> {
  if (!snapshotCache.has(season)) {
    snapshotCache.set(season, fetchJson<SnapshotSeasonFile>(`data/snapshots/${season}.json`));
  }
  return snapshotCache.get(season)!;
}

function findTeamSnapshot(
  snapshotSeason: SnapshotSeasonFile,
  gameDate: string,
  teamId: number
): SnapshotRow | null {
  for (const row of snapshotSeason.rows) {
    if (row.date === gameDate && row.teamId === teamId) {
      return row;
    }
  }
  return null;
}

function standardizeVector(raw: Float32Array, means: number[], stds: number[]): Float32Array {
  if (raw.length !== means.length || raw.length !== stds.length) {
    throw new Error(
      `Standardization length mismatch: raw=${raw.length}, means=${means.length}, stds=${stds.length}`
    );
  }

  const out = new Float32Array(raw.length);
  for (let i = 0; i < raw.length; i++) {
    const std = stds[i] === 0 ? 1 : stds[i];
    out[i] = (raw[i] - means[i]) / std;
  }
  return out;
}

function hasBadValues(arr: Float32Array): boolean {
  for (const v of arr) {
    if (!Number.isFinite(v)) return true;
    if (Math.abs(v) > 1e6) return true;
  }
  return false;
}

function resolveInputNames(session: ort.InferenceSession, meta: ModelMeta) {
  const inputNames = session.inputNames;

  const contName =
    inputNames.find((name) => meta.inputNames.includes(name)) ??
    inputNames.find((name) => ['x_cont', 'x', 'features', 'continuous_x'].includes(name)) ??
    inputNames.find((name) => name.toLowerCase().includes('cont')) ??
    inputNames[0];

  const team1Name =
    inputNames.find((name) => ['team1_id', 'team1id', 'team1'].includes(name)) ??
    inputNames.find((name) => name.toLowerCase().includes('team1')) ??
    inputNames[1];

  const team2Name =
    inputNames.find((name) => ['team2_id', 'team2id', 'team2'].includes(name)) ??
    inputNames.find((name) => name.toLowerCase().includes('team2')) ??
    inputNames[2];

  if (!contName || !team1Name || !team2Name) {
    throw new Error(`Could not resolve ONNX input names. Found: ${inputNames.join(', ')}`);
  }

  return { contName, team1Name, team2Name };
}

function buildNamedRawFeatureMap(
  featureNames: string[],
  team1Features: number[],
  team2Features: number[],
  homeIndicator: number
): Record<string, number> {
  if (
    team1Features.length !== featureNames.length ||
    team2Features.length !== featureNames.length
  ) {
    throw new Error(
      `Feature length mismatch: names=${featureNames.length}, team1=${team1Features.length}, team2=${team2Features.length}`
    );
  }

  const featureMap: Record<string, number> = {};

  for (let i = 0; i < featureNames.length; i++) {
    const baseName = featureNames[i];
    const t1 = team1Features[i];
    const t2 = team2Features[i];

    featureMap[`team1_${baseName}`] = t1;
    featureMap[`team2_${baseName}`] = t2;
    featureMap[`diff_${baseName}`] = t1 - t2;
    featureMap[`sum_${baseName}`] = t1 + t2;
  }

  featureMap['home_indicator'] = homeIndicator;
  return featureMap;
}

function buildOrderedRawVector(
  meta: ModelMeta,
  featureMap: Record<string, number>
): Float32Array {
  const values = meta.featureCols.map((name) => {
    const value = featureMap[name];
    if (value === undefined) {
      throw new Error(`Missing feature "${name}" while assembling browser inference vector`);
    }
    return value;
  });

  return new Float32Array(values);
}

async function runPredictionFromBaseFeatures(
  team1Id: number,
  team2Id: number,
  homeIndicator: number,
  featureNames: string[],
  team1Features: number[],
  team2Features: number[]
): Promise<PredictResult> {
  const [session, meta] = await Promise.all([getSession(), getModelMeta()]);

  const rawFeatureMap = buildNamedRawFeatureMap(
    featureNames,
    team1Features,
    team2Features,
    homeIndicator
  );
  const xContRaw = buildOrderedRawVector(meta, rawFeatureMap);

  if (hasBadValues(xContRaw)) {
    throw new Error('Raw input feature vector contains invalid or extremely large values');
  }

  const xCont = standardizeVector(xContRaw, meta.means, meta.stds);
  if (hasBadValues(xCont)) {
    throw new Error('Standardized input feature vector contains invalid or extremely large values');
  }

  const team1Index = meta.teamIdToIndex[String(team1Id)];
  const team2Index = meta.teamIdToIndex[String(team2Id)];

  if (team1Index === undefined) {
    throw new Error(`Missing embedding index for team ${team1Id}`);
  }
  if (team2Index === undefined) {
    throw new Error(`Missing embedding index for team ${team2Id}`);
  }

  const { contName, team1Name, team2Name } = resolveInputNames(session, meta);

  const feeds: Record<string, ort.Tensor> = {
    [contName]: new ort.Tensor('float32', xCont, [1, xCont.length]),
    [team1Name]: new ort.Tensor('int64', BigInt64Array.from([BigInt(team1Index)]), [1]),
    [team2Name]: new ort.Tensor('int64', BigInt64Array.from([BigInt(team2Index)]), [1]),
  };

  const results = await session.run(feeds);
  const outputName = meta.outputNames.find((name) => results[name] !== undefined) ?? Object.keys(results)[0];
  const output = results[outputName].data;

  return {
    team1Score: Number(output[0]),
    team2Score: Number(output[1]),
  };
}

export async function predictHistoricalGame(inputs: PredictInputs): Promise<PredictResult> {
  const snapshotSeason = await getSeasonSnapshot(inputs.season);

  const team1 = findTeamSnapshot(snapshotSeason, inputs.gameDate, inputs.team1Id);
  const team2 = findTeamSnapshot(snapshotSeason, inputs.gameDate, inputs.team2Id);

  if (!team1) {
    throw new Error(
      `No snapshot found for team ${inputs.team1Id} on ${inputs.gameDate} in season ${inputs.season}`
    );
  }

  if (!team2) {
    throw new Error(
      `No snapshot found for team ${inputs.team2Id} on ${inputs.gameDate} in season ${inputs.season}`
    );
  }

  return runPredictionFromBaseFeatures(
    inputs.team1Id,
    inputs.team2Id,
    inputs.homeIndicator,
    snapshotSeason.featureNames,
    team1.features,
    team2.features
  );
}

export async function predictUpcomingGame(inputs: UpcomingPredictInputs): Promise<PredictResult> {
  return runPredictionFromBaseFeatures(
    inputs.team1Id,
    inputs.team2Id,
    inputs.homeIndicator,
    inputs.featureNames,
    inputs.team1Features,
    inputs.team2Features
  );
}
