import { useEffect, useMemo, useState } from 'react';
import './app.css';
import { fetchJson } from './lib/fetchJson';
import { predictHistoricalGame, predictUpcomingGame } from './lib/predict';

// This file was generated by ChatGPT based on a strict and detailed outline that I created.

type TeamMap = Record<string, { id: number; displayName: string; shortName?: string; abbreviation?: string }>;

type GameIdentity = {
  id: string;
  season: number;
  date: string;
  team1Id: number;
  team1Name: string;
  team2Id: number;
  team2Name: string;
  team1Home: boolean;
  team2Home: boolean;
  team1WinsBefore?: number;
  team1LossesBefore?: number;
  team2WinsBefore?: number;
  team2LossesBefore?: number;
};

type GameRecord = GameIdentity & {
  team1Score: number;
  team2Score: number;
};

type UpcomingGameRecord = GameIdentity & {
  team1Features: number[];
  team2Features: number[];
};

type UpcomingGamesFile = {
  generatedAt: string;
  dataThrough: string | null;
  season: number;
  featureNames: string[];
  games: UpcomingGameRecord[];
};

type PredictionResult = {
  team1Score: number;
  team2Score: number;
};

type ViewMode = 'upcoming' | 'historical';
type LogLevel = 'info' | 'warn' | 'error';

type LogEvent = {
  level: LogLevel;
  message: string;
  timestamp: string;
};

function formatMatchup(game: GameIdentity) {
  const neutral = !game.team1Home && !game.team2Home;
  if (neutral) return `${game.team1Name} vs ${game.team2Name}`;
  if (game.team1Home) return `${game.team2Name} @ ${game.team1Name}`;
  return `${game.team1Name} @ ${game.team2Name}`;
}

function formatDate(dateString: string) {
  return new Date(`${dateString}T12:00:00`).toLocaleDateString();
}

function formatScoreLine(game: GameRecord) {
  const neutral = !game.team1Home && !game.team2Home;
  if (neutral || game.team1Home) {
    return `${game.team1Name} ${game.team1Score} - ${game.team2Name} ${game.team2Score}`;
  }
  return `${game.team2Name} ${game.team2Score} - ${game.team1Name} ${game.team1Score}`;
}

function formatPredictedScoreLine(game: GameIdentity, prediction: PredictionResult | null) {
  if (!prediction) return '—';
  const neutral = !game.team1Home && !game.team2Home;
  if (neutral || game.team1Home) {
    return `${game.team1Name} ${prediction.team1Score.toFixed(1)} - ${game.team2Name} ${prediction.team2Score.toFixed(1)}`;
  }
  return `${game.team2Name} ${prediction.team2Score.toFixed(1)} - ${game.team1Name} ${prediction.team1Score.toFixed(1)}`;
}

function predictedWinner(game: GameIdentity, prediction: PredictionResult | null) {
  if (!prediction) return '';
  return prediction.team1Score >= prediction.team2Score ? game.team1Name : game.team2Name;
}

function actualWinner(game: GameRecord) {
  return game.team1Score >= game.team2Score ? game.team1Name : game.team2Name;
}

function winnerCorrect(game: GameRecord, prediction: PredictionResult | null) {
  if (!prediction) return '';
  return predictedWinner(game, prediction) === actualWinner(game) ? 'Yes' : 'No';
}

function rmseScore(game: GameRecord, prediction: PredictionResult | null) {
  if (!prediction) return '';
  const predSpread = prediction.team1Score - prediction.team2Score;
  const actualSpread = game.team1Score - game.team2Score;
  const mse = (
    Math.pow(prediction.team1Score - game.team1Score, 2) +
    Math.pow(prediction.team2Score - game.team2Score, 2) +
    Math.pow(predSpread - actualSpread, 2)
  ) / 3;
  return Math.sqrt(mse).toFixed(2);
}

function formatRecord(wins?: number, losses?: number) {
  if (wins == null || losses == null) return '—';
  return `(${wins}-${losses})`;
}

function homeIndicator(game: GameIdentity) {
  if (!game.team1Home && !game.team2Home) return 0;
  return game.team1Home ? 1 : -1;
}

export default function App() {
  const [mode, setMode] = useState<ViewMode>('upcoming');
  const [games, setGames] = useState<GameRecord[]>([]);
  const [upcomingData, setUpcomingData] = useState<UpcomingGamesFile | null>(null);
  const [selectedSeason, setSelectedSeason] = useState<string>('');
  const [selectedTeamId, setSelectedTeamId] = useState<string>('');
  const [selectedGameId, setSelectedGameId] = useState<string>('');
  const [prediction, setPrediction] = useState<PredictionResult | null>(null);
  const [loadingPrediction, setLoadingPrediction] = useState(false);
  const [loadingData, setLoadingData] = useState(true);
  const [error, setError] = useState<string>('');
  const [logs, setLogs] = useState<LogEvent[]>([]);

  const addLog = (level: LogLevel, message: string) => {
    setLogs((prev) => [{ level, message, timestamp: new Date().toLocaleTimeString() }, ...prev].slice(0, 25));
    if (level === 'error') console.error(message);
    else if (level === 'warn') console.warn(message);
    else console.log(message);
  };

  useEffect(() => {
    (async () => {
      setLoadingData(true);
      try {
        addLog('info', 'Loading teams, historical games, and upcoming schedule');

        const [teamData, gameData] = await Promise.all([
          fetchJson<TeamMap>('data/teams.json'),
          fetchJson<GameRecord[]>('data/games/all_games.json'),
        ]);

        setGames(gameData);
        const seasons = [...new Set(gameData.map((g) => g.season))].sort((a, b) => b - a);
        if (seasons.length > 0) setSelectedSeason(String(seasons[0]));

        addLog('info', `Loaded ${Object.keys(teamData).length} teams`);
        addLog('info', `Loaded ${gameData.length} historical games`);

        try {
          const future = await fetchJson<UpcomingGamesFile>('data/upcoming_games.json');
          setUpcomingData(future);
          addLog('info', `Loaded ${future.games.length} upcoming games for season ${future.season}`);

          if (future.games.length === 0) {
            setMode('historical');
            addLog('warn', 'No upcoming games are currently available; showing historical mode');
          }
        } catch (futureErr) {
          const message = futureErr instanceof Error ? futureErr.message : 'Could not load upcoming games';
          setMode('historical');
          addLog('warn', `Upcoming-game data unavailable: ${message}`);
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Unknown load error';
        setError(message);
        addLog('error', message);
      } finally {
        setLoadingData(false);
      }
    })();
  }, []);

  const seasons = useMemo(
    () => [...new Set(games.map((g) => g.season))].sort((a, b) => b - a),
    [games]
  );

  const seasonGames = useMemo(
    () => games.filter((g) => String(g.season) === selectedSeason),
    [games, selectedSeason]
  );

  const activeGames = useMemo<Array<GameRecord | UpcomingGameRecord>>(
    () => mode === 'upcoming' ? (upcomingData?.games ?? []) : seasonGames,
    [mode, upcomingData, seasonGames]
  );

  const teamOptions = useMemo(() => {
    const map = new Map<number, string>();
    for (const game of activeGames) {
      map.set(game.team1Id, game.team1Name);
      map.set(game.team2Id, game.team2Name);
    }
    return [...map.entries()]
      .map(([id, name]) => ({ id, name }))
      .sort((a, b) => a.name.localeCompare(b.name));
  }, [activeGames]);

  const filteredGames = useMemo(() => {
    if (!selectedTeamId) return activeGames;
    const tid = Number(selectedTeamId);
    return activeGames.filter((g) => g.team1Id === tid || g.team2Id === tid);
  }, [activeGames, selectedTeamId]);

  const selectedGame = useMemo(
    () => filteredGames.find((game) => game.id === selectedGameId) ?? null,
    [filteredGames, selectedGameId]
  );

  const selectedHistoricalGame = mode === 'historical' ? selectedGame as GameRecord | null : null;
  const selectedUpcomingGame = mode === 'upcoming' ? selectedGame as UpcomingGameRecord | null : null;

  useEffect(() => {
    setSelectedTeamId('');
    setSelectedGameId('');
    setPrediction(null);
    setError('');
  }, [mode, selectedSeason]);

  useEffect(() => {
    if (teamOptions.length > 0 && selectedTeamId) {
      const exists = teamOptions.some((t) => String(t.id) === selectedTeamId);
      if (!exists) setSelectedTeamId('');
    }
  }, [teamOptions, selectedTeamId]);

  useEffect(() => {
    if (filteredGames.length > 0) {
      setSelectedGameId((prev) => {
        const exists = filteredGames.some((g) => g.id === prev);
        return exists ? prev : filteredGames[0].id;
      });
    } else {
      setSelectedGameId('');
    }
  }, [filteredGames]);

  useEffect(() => {
    setPrediction(null);
    setError('');
  }, [selectedGameId]);

  const onPredict = async () => {
    if (!selectedGame) return;

    setLoadingPrediction(true);
    setError('');
    addLog('info', `Running ${mode} prediction for game ${selectedGame.id}`);

    try {
      let result: PredictionResult;

      if (mode === 'upcoming') {
        if (!selectedUpcomingGame || !upcomingData) {
          throw new Error('Upcoming-game feature data is unavailable');
        }
        result = await predictUpcomingGame({
          team1Id: selectedUpcomingGame.team1Id,
          team2Id: selectedUpcomingGame.team2Id,
          homeIndicator: homeIndicator(selectedUpcomingGame),
          featureNames: upcomingData.featureNames,
          team1Features: selectedUpcomingGame.team1Features,
          team2Features: selectedUpcomingGame.team2Features,
        });
      } else {
        if (!selectedHistoricalGame) throw new Error('Historical game is unavailable');
        result = await predictHistoricalGame({
          season: selectedHistoricalGame.season,
          gameDate: selectedHistoricalGame.date,
          team1Id: selectedHistoricalGame.team1Id,
          team2Id: selectedHistoricalGame.team2Id,
          homeIndicator: homeIndicator(selectedHistoricalGame),
        });
      }

      setPrediction(result);
      addLog('info', `Prediction completed for ${formatMatchup(selectedGame)}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : 'Prediction failed';
      setError(message);
      setPrediction(null);
      addLog('error', message);
    } finally {
      setLoadingPrediction(false);
    }
  };

  const upcomingDataNote = upcomingData?.dataThrough
    ? `Completed ${upcomingData.season} game data through ${formatDate(upcomingData.dataThrough)}`
    : `No completed ${upcomingData?.season ?? ''} games are in the statistical history yet`;

  return (
    <div className="page-shell">
      <header className="hero-card">
        <div>
          <p className="eyebrow">
            {mode === 'upcoming' ? 'Future Game Predictor' : 'Historical Game Predictor'}
          </p>
          <h1>
            {mode === 'upcoming'
              ? 'NCAA men\'s basketball upcoming-game predictor'
              : 'NCAA men\'s basketball backtest viewer'}
          </h1>
          <p className="hero-subtitle">
            {mode === 'upcoming'
              ? 'Choose a scheduled game that has not been played yet. Predictions use only games that have actually been completed.'
              : 'Select a season, optionally filter by team, then choose a completed game.'}
          </p>

          <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1rem', flexWrap: 'wrap' }}>
            <button
              className="predict-button"
              onClick={() => setMode('upcoming')}
              disabled={loadingData || !upcomingData || upcomingData.games.length === 0}
              style={{ opacity: mode === 'upcoming' ? 1 : 0.65 }}
            >
              Upcoming games
            </button>
            <button
              className="predict-button"
              onClick={() => setMode('historical')}
              disabled={loadingData || games.length === 0}
              style={{ opacity: mode === 'historical' ? 1 : 0.65 }}
            >
              Historical backtest
            </button>
          </div>
        </div>
      </header>

      <main className="layout-grid">
        <section className="panel controls-panel">
          <h2>{mode === 'upcoming' ? 'Choose an upcoming game' : 'Choose a historical game'}</h2>

          {mode === 'historical' && (
            <>
              <label className="field-label" htmlFor="season-select">Season</label>
              <select
                id="season-select"
                className="input"
                value={selectedSeason}
                onChange={(e) => setSelectedSeason(e.target.value)}
                disabled={loadingData || seasons.length === 0}
              >
                {seasons.map((season) => (
                  <option key={season} value={String(season)}>{season}</option>
                ))}
              </select>
            </>
          )}

          {mode === 'upcoming' && upcomingData && (
            <div style={{ marginBottom: '1rem' }}>
              <strong>Season {upcomingData.season}</strong>
              <div style={{ marginTop: '0.25rem', opacity: 0.75, fontSize: '0.9rem' }}>
                {upcomingDataNote}. Unplayed scheduled games are never used as statistical history.
              </div>
            </div>
          )}

          <label className="field-label" htmlFor="team-select">Team filter (optional)</label>
          <select
            id="team-select"
            className="input"
            value={selectedTeamId}
            onChange={(e) => setSelectedTeamId(e.target.value)}
            disabled={loadingData || teamOptions.length === 0}
          >
            <option value="">All teams</option>
            {teamOptions.map((team) => (
              <option key={team.id} value={String(team.id)}>{team.name}</option>
            ))}
          </select>

          <label className="field-label" htmlFor="game-select">Matchup</label>
          <select
            id="game-select"
            className="input"
            value={selectedGameId}
            onChange={(e) => setSelectedGameId(e.target.value)}
            disabled={loadingData || filteredGames.length === 0}
          >
            {filteredGames.map((game) => (
              <option key={game.id} value={game.id}>
                {game.date} — {formatMatchup(game)}
              </option>
            ))}
          </select>

          <button
            className="predict-button"
            onClick={onPredict}
            disabled={!selectedGame || loadingPrediction || loadingData}
          >
            {loadingPrediction
              ? 'Predicting…'
              : mode === 'upcoming'
                ? 'Predict upcoming game'
                : 'Predict historical result'}
          </button>

          {error && (
            <div className="error-banner">
              <strong>Error:</strong> {error}
            </div>
          )}
        </section>

        {selectedGame && (
          <section className="panel score-panel">
            <div className="score-topline">
              <span className="sport-label">NCAA men&apos;s basketball</span>
              <span className="final-badge">
                {mode === 'upcoming' ? 'UPCOMING' : 'Final'}
              </span>
            </div>

            <div className="scoreboard-body">
              <div className="team-block">
                <div className="team-name">{selectedGame.team1Name}</div>
                <div className="team-record">
                  {formatRecord(selectedGame.team1WinsBefore, selectedGame.team1LossesBefore)}
                </div>
              </div>

              <div className="score-block">
                {mode === 'historical' && selectedHistoricalGame ? (
                  <>
                    <span className="score-value">{selectedHistoricalGame.team1Score}</span>
                    <span className="score-separator">-</span>
                    <span className="score-value">{selectedHistoricalGame.team2Score}</span>
                  </>
                ) : (
                  <>
                    <span className="score-value">{prediction ? prediction.team1Score.toFixed(1) : '—'}</span>
                    <span className="score-separator">-</span>
                    <span className="score-value">{prediction ? prediction.team2Score.toFixed(1) : '—'}</span>
                  </>
                )}
              </div>

              <div className="team-block team-block-right">
                <div className="team-name">{selectedGame.team2Name}</div>
                <div className="team-record">
                  {formatRecord(selectedGame.team2WinsBefore, selectedGame.team2LossesBefore)}
                </div>
              </div>
            </div>

            <div className="scoreboard-footer">
              <span>{formatDate(selectedGame.date)}</span>
              <span>{mode === 'upcoming' ? 'Model prediction' : formatMatchup(selectedGame)}</span>
            </div>
          </section>
        )}

        {selectedHistoricalGame && (
          <section className="panel result-panel">
            <h2>Prediction result</h2>
            <div className="result-grid">
              <div className="result-row">
                <span className="result-label">Matchup</span>
                <span className="result-value">{formatMatchup(selectedHistoricalGame)}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Actual score</span>
                <span className="result-value">{formatScoreLine(selectedHistoricalGame)}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Predicted score</span>
                <span className="result-value muted">{formatPredictedScoreLine(selectedHistoricalGame, prediction)}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Actual winner</span>
                <span className="result-value">{actualWinner(selectedHistoricalGame)}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Predicted winner</span>
                <span className="result-value muted">{prediction ? predictedWinner(selectedHistoricalGame, prediction) : '—'}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Winner prediction correct</span>
                <span className="result-value muted">{prediction ? winnerCorrect(selectedHistoricalGame, prediction) : '—'}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Score</span>
                <span className="result-value muted">{prediction ? rmseScore(selectedHistoricalGame, prediction) : '—'}</span>
              </div>
            </div>
          </section>
        )}

        {selectedUpcomingGame && (
          <section className="panel result-panel">
            <h2>Upcoming-game prediction</h2>
            <div className="result-grid">
              <div className="result-row">
                <span className="result-label">Status</span>
                <span className="result-value">UPCOMING — game has not been played</span>
              </div>
              <div className="result-row">
                <span className="result-label">Matchup</span>
                <span className="result-value">{formatMatchup(selectedUpcomingGame)}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Game date</span>
                <span className="result-value">{formatDate(selectedUpcomingGame.date)}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Predicted score</span>
                <span className="result-value muted">{formatPredictedScoreLine(selectedUpcomingGame, prediction)}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Predicted winner</span>
                <span className="result-value muted">{prediction ? predictedWinner(selectedUpcomingGame, prediction) : '—'}</span>
              </div>
              <div className="result-row">
                <span className="result-label">Completed data used through</span>
                <span className="result-value">
                  {upcomingData?.dataThrough ? formatDate(upcomingData.dataThrough) : 'No games completed yet this season'}
                </span>
              </div>
            </div>
          </section>
        )}

        <section className="panel log-panel">
          <h2>Activity log</h2>
          <div className="log-list">
            {logs.length === 0 ? (
              <div className="log-empty">No events yet.</div>
            ) : (
              logs.map((entry, index) => (
                <div key={`${entry.timestamp}-${index}`} className={`log-item log-${entry.level}`}>
                  <div className="log-meta">[{entry.timestamp}] {entry.level.toUpperCase()}</div>
                  <div>{entry.message}</div>
                </div>
              ))
            )}
          </div>
        </section>
      </main>
    </div>
  );
}
