import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'

// This file was generated by ChatGPT based on a strict and detailed outline that I created.

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
